# Imagen base con JDK 21
FROM openjdk:21-jdk
# Define un argumento para el archivo JAR
ARG JAR_FILE=target/empresa-0.0.1.jar

# Copia el archivo JAR a la imagen
COPY ${JAR_FILE} app_EMPRESA.jar

# Expone el puerto 8080
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "/app_EMPRESA.jar"]